// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncbgibxbscpogzytgdlz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jYmdpYnhic2Nwb2d6eXRnZGx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwMzM3MDYsImV4cCI6MjA1MTYwOTcwNn0.CbC6a37H_gzfUYv-z3m535x1gQPzyVMQQbLHia3BqAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);